version: '3.9'

services:
  openacs:
    image: oupfiz5/openacs-s6:latest
    restart: always
    env_file:
      - .env
    volumes:
      - content:/var/www/openacs/content-repository-content-files
      - ./rootfs/usr/local/ns/conf/:/usr/local/ns/conf/
    depends_on:
      - postgres
    ports:
      - ${OACS_LISTEN_PORT}:8000
    healthcheck:
      test: ["CMD-SHELL", "wget -qO - http://localhost:${OACS_LISTEN_PORT}/SYSTEM/openacs-test || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
        POSTGRES_PASSWORD: testing
        POSTGRES_USER: openacs
        POSTGRES_DB: openacs
    env_file:
      - .env
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  content:
