version: '3.9'

services:
  openacs:
    image: oupfiz5/openacs-s6:latest
    env_file:
      - .env
    volumes:
      - content:/var/www/openacs/content-repository-content-files
      - ./rootfs/usr/local/ns/conf/:/usr/local/ns/conf/
    depends_on:
      - postgres
    ports:
      - ${OACS_LISTEN_PORT}:8000
    healthcheck:
      test: ["CMD-SHELL", "wget -qO - http://localhost:8000/SYSTEM/openacs-test || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2

  postgres:
    image: datacore/postgresql:${POSTGRES_DATACORE_TAG}
    env_file:
      - .env
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  content:
